package com.gamevh.util;

import java.text.DecimalFormat;
import java.util.List;

import com.gamevh.entities.OrderData;
import com.gamevh.entities.OrderDetail;

public class mail_CONSTANT {

	public static String mail_order(String username, String source) {

		String welcome = "<!-- © 2018 Shift Technologies. All rights reserved. -->\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"table-layout:fixed;background-color:#f9f9f9\" id=\"bodyTable\">\r\n"
				+ "    <tbody>\r\n"
				+ "        <tr>\r\n"
				+ "            <td style=\"padding-right:10px;padding-left:10px;\" align=\"center\" valign=\"top\" id=\"bodyCell\">\r\n"
				+ "\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"wrapperBody\" style=\"max-width:600px\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td align=\"center\" valign=\"top\">\r\n"
				+ "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"tableCard\" style=\"background-color:#fff;border-color:#e5e5e5;border-style:solid;border-width:0 1px 1px 1px;\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"background-color:#00d2f4;font-size:1px;line-height:3px\" class=\"topBorder\" height=\"3\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "\r\n"
				+ "                                        <tr style=\"margin-top: 1.5em;\">\r\n"
				+ "                                            <td style=\"padding-bottom: 5px; padding-left: 20px; padding-right: 20px;\" align=\"center\" valign=\"top\" class=\"mainTitle\">\r\n"
				+ "                                                <h2 class=\"text\" style=\"color:#000;font-family:Poppins,Helvetica,Arial,sans-serif;font-size:28px;font-weight:500;font-style:normal;letter-spacing:normal;line-height:36px;text-transform:none;text-align:center;padding:0;margin:0;margin-top: 1.5em;\">Hi \""+username+"\"</h2>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding-bottom: 30px; padding-left: 20px; padding-right: 20px;\" align=\"center\" valign=\"top\" class=\"subTitle\">\r\n"
				+ "                                                <h4 class=\"text\" style=\"color:#999;font-family:Poppins,Helvetica,Arial,sans-serif;font-size:16px;font-weight:500;font-style:normal;letter-spacing:normal;line-height:24px;text-transform:none;text-align:center;padding:0;margin:0\">Xác nhận thanh toán thành công !</h4>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding-left:20px;padding-right:20px\" align=\"center\" valign=\"top\" class=\"containtTable ui-sortable\">\r\n"
				+ "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"tableDescription\" style=\"\">\r\n"
				+ "                                                    <tbody>\r\n"
				+ "                                                        <tr>\r\n"
				+ "                                                            <td style=\"padding-bottom: 20px;\" align=\"center\" valign=\"top\" class=\"description\">\r\n"
				+ "                                                                <p class=\"text\" style=\"color:#666;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:14px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:22px;text-transform:none;text-align:center;padding:0;margin:0\">Chúc mừng bạn đã thanh toán thành công tựa game này.</p>\r\n"
				+ "                                                                <p class=\"text\" style=\"color:#666;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:14px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:22px;text-transform:none;text-align:center;padding:0;margin:0\">Link game của bạn.</p>\r\n"
				+ "                                                                <p class=\"text\" style=\"color:#666;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:14px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:22px;text-transform:none;text-align:center;padding:0;margin:0\">"+source+"</p>\r\n"
				+ "                                                            </td>\r\n"
				+ "                                                        </tr>\r\n"
				+ "                                                    </tbody>\r\n"
				+ "                                                </table>\r\n"
				+ "\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"font-size:1px;line-height:1px\" height=\"20\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                </table>\r\n"
				+ "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"space\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"font-size:1px;line-height:1px\" height=\"30\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                </table>\r\n"
				+ "                            </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table>\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"wrapperFooter\" style=\"max-width:600px\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td align=\"center\" valign=\"top\">\r\n"
				+ "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"footer\">\r\n"
				+ "                                    <tbody>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding-top:10px;padding-bottom:10px;padding-left:10px;padding-right:10px\" align=\"center\" valign=\"top\" class=\"socialLinks\">\r\n"
				+ "                                                <a href=\"#facebook-link\" style=\"display:inline-block\" target=\"_blank\" class=\"facebook\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/facebook.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#twitter-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"twitter\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/twitter.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#pintrest-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"pintrest\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/pintrest.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#instagram-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"instagram\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/instagram.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                                <a href=\"#linkdin-link\" style=\"display: inline-block;\" target=\"_blank\" class=\"linkdin\">\r\n"
				+ "                                                    <img alt=\"\" border=\"0\" src=\"http://email.aumfusion.com/vespro/img/social/light/linkdin.png\" style=\"height:auto;width:100%;max-width:40px;margin-left:2px;margin-right:2px\" width=\"40\">\r\n"
				+ "                                                </a>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding: 10px 10px 5px;\" align=\"center\" valign=\"top\" class=\"brandInfo\">\r\n"
				+ "                                                <p class=\"text\" style=\"color:#bbb;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:20px;text-transform:none;text-align:center;padding:0;margin:0\">©&nbsp;Vespro Inc. | 800 Broadway, Suite 1500 | New York, NY 000123, USA.</p>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding: 0px 10px 20px;\" align=\"center\" valign=\"top\" class=\"footerLinks\">\r\n"
				+ "                                                <p class=\"text\" style=\"color:#bbb;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:20px;text-transform:none;text-align:center;padding:0;margin:0\"> <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">View Web Version </a>&nbsp;|&nbsp; <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">Email Preferences </a>&nbsp;|&nbsp;\r\n"
				+ "                                                    <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">Privacy Policy</a>\r\n"
				+ "                                                </p>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"padding: 0px 10px 10px;\" align=\"center\" valign=\"top\" class=\"footerEmailInfo\">\r\n"
				+ "                                                <p class=\"text\" style=\"color:#bbb;font-family:'Open Sans',Helvetica,Arial,sans-serif;font-size:12px;font-weight:400;font-style:normal;letter-spacing:normal;line-height:20px;text-transform:none;text-align:center;padding:0;margin:0\">If you have any quetions please contact us <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">support@mail.com.</a>\r\n"
				+ "                                                    <br> <a href=\"#\" style=\"color:#bbb;text-decoration:underline\" target=\"_blank\">Unsubscribe</a> from our mailing lists</p>\r\n"
				+ "                                            </td>\r\n"
				+ "                                        </tr>\r\n"
				+ "\r\n"
				+ "                                        <tr>\r\n"
				+ "                                            <td style=\"font-size:1px;line-height:1px\" height=\"30\">&nbsp;</td>\r\n"
				+ "                                        </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                </table>\r\n"
				+ "                            </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td style=\"font-size:1px;line-height:1px\" height=\"30\">&nbsp;</td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table>\r\n"
				+ "            </td>\r\n"
				+ "        </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "</table>";
		return welcome;
	}
	
	public static String mail_Welcome(String fullname, String username, String password) {

		String welcome = "<!DOCTYPE html\r\n"
				+ "    PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\">\r\n"
				+ "    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
				+ "    <title>PropTech Kenya Welcome Email</title>\r\n"
				+ "    <!-- Designed by https://github.com/kaytcat --><!-- Robot header image designed by Freepik.com -->\r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "        @import url(https://fonts.googleapis.com/css?family=Nunito);\r\n"
				+ "\r\n"
				+ "        /* Take care of image borders and formatting */\r\n"
				+ "\r\n"
				+ "        img {\r\n"
				+ "            max-width: 600px;\r\n"
				+ "            outline: none;\r\n"
				+ "            text-decoration: none;\r\n"
				+ "            -ms-interpolation-mode: bicubic;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        html {\r\n"
				+ "            margin: 0;\r\n"
				+ "            padding: 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        a {\r\n"
				+ "            text-decoration: none;\r\n"
				+ "            border: 0;\r\n"
				+ "            outline: none;\r\n"
				+ "            color: #bbbbbb;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        a img {\r\n"
				+ "            border: none;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* General styling */\r\n"
				+ "\r\n"
				+ "        td,\r\n"
				+ "        h1,\r\n"
				+ "        h2,\r\n"
				+ "        h3 {\r\n"
				+ "            font-family: Helvetica, Arial, sans-serif;\r\n"
				+ "            font-weight: 400;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        td {\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        body {\r\n"
				+ "            -webkit-font-smoothing: antialiased;\r\n"
				+ "            -webkit-text-size-adjust: none;\r\n"
				+ "            width: 100%;\r\n"
				+ "            height: 100%;\r\n"
				+ "            color: #666;\r\n"
				+ "            background: #fff;\r\n"
				+ "            font-size: 16px;\r\n"
				+ "            height: 100vh;\r\n"
				+ "            width: 100%;\r\n"
				+ "            padding: 0px;\r\n"
				+ "            margin: 0px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        table {\r\n"
				+ "            border-collapse: collapse !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .headline {\r\n"
				+ "            color: #444;\r\n"
				+ "            font-size: 36px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .force-full-width {\r\n"
				+ "            width: 100% !important;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "    <style media=\"screen\" type=\"text/css\">\r\n"
				+ "        @media screen {\r\n"
				+ "\r\n"
				+ "            td,\r\n"
				+ "            h1,\r\n"
				+ "            h2,\r\n"
				+ "            h3 {\r\n"
				+ "                font-family: 'Nunito', 'Helvetica Neue', 'Arial', 'sans-serif' !important;\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "    <style media=\"only screen and (max-width: 480px)\" type=\"text/css\">\r\n"
				+ "        /* Mobile styles */\r\n"
				+ "\r\n"
				+ "        @media only screen and (max-width: 480px) {\r\n"
				+ "\r\n"
				+ "            table[class=\"w320\"] {\r\n"
				+ "                width: 320px !important;\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body bgcolor=\"#fff\" class=\"body\"\r\n"
				+ "    style=\"padding:20px; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none\">\r\n"
				+ "    <table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\">\r\n"
				+ "        <tbody>\r\n"
				+ "            <tr>\r\n"
				+ "                <td align=\"center\" bgcolor=\"#fff\" class=\"\" valign=\"top\" width=\"100%\">\r\n"
				+ "                    <center class=\"\">\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"w320\" style=\"margin: 0 auto;\" width=\"600\">\r\n"
				+ "                            <tbody>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td align=\"center\" class=\"\" valign=\"top\">\r\n"
				+ "                                        <table cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"100%\">\r\n"
				+ "                                        </table>\r\n"
				+ "                                        <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"\"\r\n"
				+ "                                            style=\"margin: 0 auto; width: 100%; margin-top: 100px;\">\r\n"
				+ "                                            <tbody style=\"margin-top: 15px;\">\r\n"
				+ "                                                <tr class=\"\">\r\n"
				+ "                                                    <td class=\"\">\r\n"
				+ "                                                        <img alt=\"robot picture\" width=\"350\"\r\n"
				+ "                                                            src=\"https://lh3.googleusercontent.com/pw/AMWts8BE52AhhQd3jDG4W2RUxzaAq69PcixOhv_nV9VI2IxljwxzDHr6XShIYlSfq1io_5IdAJNePdcUHIDRzYcMJZFaYKf7N4e39CVIwWjUOcjVcW1ra2A4_oecW0PLytJyocXmFFNRAAtQQymNTGxxWD0=w960-h326\">\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                                <tr class=\"\">\r\n"
				+ "                                                    <td class=\"headline\" style=\"font-weight: 750;\">GAMESVH</td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td>\r\n"
				+ "                                                        <center class=\"\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" class=\"\"\r\n"
				+ "                                                                style=\"margin: 0 auto; width: 75%;\">\r\n"
				+ "                                                                <tbody class=\"\">\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"\"\r\n"
				+ "                                                                            style=\"color:#444; font-weight: 400; text-align: justify; padding-top: 15px;\">\r\n"
				+ "                                                                            <strong>Cám ơn bạn đã sử dụng website\r\n"
				+ "                                                                                GamesVH.</strong> <br> <br>\r\n"
				+ "\r\n"
				+ "                                                                            Xin chào " + fullname + ", GamesVH rất vui vì bạn đã đăng\r\n"
				+ "                                                                            ký để trở thành một thành viên của chúng\r\n"
				+ "                                                                            tôi. Hy vọng chúng tôi có thể đem đến những trải\r\n"
				+ "                                                                            nghiệm mua sắm thú vị cho bạn. Chúc bạn có\r\n"
				+ "                                                                            một ngày tốt lành!<br>\r\n"
				+ "                                                                            <br>\r\n"
				+ "\r\n"
				+ "                                                                            Đây là thông tin tài khoản bạn đã đăng ký:\r\n"
				+ "                                                                            <br>\r\n"
				+ "                                                                            <p\r\n"
				+ "                                                                                style=\"font-size: 1.5em; font-weight: 750;\">\r\n"
				+ "                                                                                <strong>USERNAME: " + username + "</strong>\r\n"
				+ "                                                                                <br>\r\n"
				+ "                                                                                <strong>PASSWORD: " + password + "</strong>\r\n"
				+ "                                                                            </p>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "                                                                            <strong><em>Vui lòng không chia sẻ mail\r\n"
				+ "                                                                                này cho bất kỳ ai nhằm bảo mật thông tin\r\n"
				+ "                                                                                tài\r\n"
				+ "                                                                                khoản của bạn!</em> </strong> <br> <br>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "                                                                        </td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td style=\"text-align: right;\">Trân trọng,\r\n"
				+ "                                                                            Đội ngũ GamesVH</td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </center>\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "\r\n"
				+ "                                        </table>\r\n"
				+ "\r\n"
				+ "                                        <div style=\"margin-top: 20px; margin-bottom: 5px; border: 1px solid #e7e7e7;\">\r\n"
				+ "                                        </div>\r\n"
				+ "                                        <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\r\n"
				+ "                                            style=\"margin: 0 auto; margin-bottom: 5px;\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td style=\"text-align: justify; padding-top: 15px;\">\r\n"
				+ "                                                        <em> Nếu quý khách có bất cứ câu hỏi nào, đừng ngần ngại liên\r\n"
				+ "                                                            lạc với\r\n"
				+ "                                                            chúng tôi qua Tổng đài +0123 456 789. Đội ngũ GamesVH sẽ\r\n"
				+ "                                                            luôn sẵn\r\n"
				+ "                                                            sàng để hỗ trợ quý khách.</em>\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                            </tbody>\r\n"
				+ "                        </table>\r\n"
				+ "                    </center>\r\n"
				+ "                </td>\r\n"
				+ "            </tr>\r\n"
				+ "        </tbody>\r\n"
				+ "    </table>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
		return welcome;
	}
	
	public static String mail_Order_Success(OrderData orderData, List<OrderDetail> orderDetails) {
		String orderDetail = "";
		String couponCode = orderData.getCouponCode();
		if(couponCode == null) {
			couponCode = "...";
		}
		int index = 1;
		for (OrderDetail od : orderDetails) {
			orderDetail += "<tr>\r\n"
					+ "                                                    <td style=\"padding: 15px 0px; border-bottom: 1px solid #e7e7e7;\">" + index + "\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                    <td style=\"padding: 15px 0px; border-bottom: 1px solid #e7e7e7;\">\r\n"
					+ "                                                        " + od.getProduct().getName() + "</td>\r\n"
					+ "                                                    <td style=\"padding: 15px 0px; border-bottom: 1px solid #e7e7e7;\">" + od.getQty() + "\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                    <td style=\"padding: 15px 0px; border-bottom: 1px solid #e7e7e7;\">\r\n"
					+ "                                                        " + formatNumber(od.getPrice()) + " VND</td>\r\n"
					+ "                                                </tr>";
			index++;
		}
		
		String content = "<!DOCTYPE html\r\n"
				+ "    PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\">\r\n"
				+ "    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
				+ "    <title>PropTech Kenya Welcome Email</title>\r\n"
				+ "    <!-- Designed by https://github.com/kaytcat --><!-- Robot header image designed by Freepik.com -->\r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "        @import url(https://fonts.googleapis.com/css?family=Nunito);\r\n"
				+ "\r\n"
				+ "        /* Take care of image borders and formatting */\r\n"
				+ "\r\n"
				+ "        img {\r\n"
				+ "            max-width: 600px;\r\n"
				+ "            outline: none;\r\n"
				+ "            text-decoration: none;\r\n"
				+ "            -ms-interpolation-mode: bicubic;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        html {\r\n"
				+ "            margin: 0;\r\n"
				+ "            padding: 0;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        a {\r\n"
				+ "            text-decoration: none;\r\n"
				+ "            border: 0;\r\n"
				+ "            outline: none;\r\n"
				+ "            color: #bbbbbb;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        a img {\r\n"
				+ "            border: none;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        /* General styling */\r\n"
				+ "\r\n"
				+ "        td,\r\n"
				+ "        h1,\r\n"
				+ "        h2,\r\n"
				+ "        h3 {\r\n"
				+ "            font-family: Helvetica, Arial, sans-serif;\r\n"
				+ "            font-weight: 400;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        td {\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        body {\r\n"
				+ "            -webkit-font-smoothing: antialiased;\r\n"
				+ "            -webkit-text-size-adjust: none;\r\n"
				+ "            width: 100%;\r\n"
				+ "            height: 100%;\r\n"
				+ "            color: #666;\r\n"
				+ "            background: #fff;\r\n"
				+ "            font-size: 16px;\r\n"
				+ "            height: 100vh;\r\n"
				+ "            width: 100%;\r\n"
				+ "            padding: 0px;\r\n"
				+ "            margin: 0px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        table {\r\n"
				+ "            border-collapse: collapse !important;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .headline {\r\n"
				+ "            color: #444;\r\n"
				+ "            font-size: 36px;\r\n"
				+ "        }\r\n"
				+ "\r\n"
				+ "        .force-full-width {\r\n"
				+ "            width: 100% !important;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "    <style media=\"screen\" type=\"text/css\">\r\n"
				+ "        @media screen {\r\n"
				+ "\r\n"
				+ "            td,\r\n"
				+ "            h1,\r\n"
				+ "            h2,\r\n"
				+ "            h3 {\r\n"
				+ "                font-family: 'Nunito', 'Helvetica Neue', 'Arial', 'sans-serif' !important;\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "    <style media=\"only screen and (max-width: 480px)\" type=\"text/css\">\r\n"
				+ "        /* Mobile styles */\r\n"
				+ "\r\n"
				+ "        @media only screen and (max-width: 480px) {\r\n"
				+ "\r\n"
				+ "            table[class=\"w320\"] {\r\n"
				+ "                width: 320px !important;\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body bgcolor=\"#fff\" class=\"body\"\r\n"
				+ "    style=\"padding:20px; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none\">\r\n"
				+ "    <table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\">\r\n"
				+ "        <tbody>\r\n"
				+ "            <tr>\r\n"
				+ "                <td align=\"center\" bgcolor=\"#fff\" class=\"\" valign=\"top\" width=\"100%\">\r\n"
				+ "                    <center class=\"\">\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"w320\" style=\"margin: 0 auto;\" width=\"600\">\r\n"
				+ "                            <tbody>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td align=\"center\" class=\"\" valign=\"top\">\r\n"
				+ "                                        <table cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"100%\">\r\n"
				+ "                                        </table>\r\n"
				+ "                                        <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"\"\r\n"
				+ "                                            style=\"margin: 0 auto; width: 100%; margin-top: 100px;\">\r\n"
				+ "                                            <tbody style=\"margin-top: 15px;\">\r\n"
				+ "                                                <tr class=\"\">\r\n"
				+ "                                                    <td class=\"\">\r\n"
				+ "                                                        <img alt=\"robot picture\" width=\"350\"\r\n"
				+ "                                                            src=\"https://lh3.googleusercontent.com/pw/AMWts8BE52AhhQd3jDG4W2RUxzaAq69PcixOhv_nV9VI2IxljwxzDHr6XShIYlSfq1io_5IdAJNePdcUHIDRzYcMJZFaYKf7N4e39CVIwWjUOcjVcW1ra2A4_oecW0PLytJyocXmFFNRAAtQQymNTGxxWD0=w960-h326\">\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                                <tr class=\"\">\r\n"
				+ "                                                    <td class=\"headline\" style=\"font-weight: 750;\">GAMESVH</td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td>\r\n"
				+ "                                                        <center class=\"\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" class=\"\"\r\n"
				+ "                                                                style=\"margin: 0 auto; width: 75%;\">\r\n"
				+ "                                                                <tbody class=\"\">\r\n"
				+ "                                                                    <tr class=\"\">\r\n"
				+ "                                                                        <td\r\n"
				+ "                                                                            style=\"text-align: right; padding-top: 15px;\">\r\n"
				+ "                                                                            ĐƠN HÀNG:\r\n"
				+ "                                                                            " + orderData.getOrderId() + "</td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"\"\r\n"
				+ "                                                                            style=\"color:#444; font-weight: 400; text-align: justify; padding-top: 15px;\">\r\n"
				+ "                                                                            <strong>Cám ơn quý khách đã mua hàng tại\r\n"
				+ "                                                                                GamesVH.</strong> <br> <br>\r\n"
				+ "\r\n"
				+ "                                                                            Xin chào " + orderData.getFullname() + ", GamesVH rất vui đã nhận được\r\n"
				+ "                                                                            đơn đặt hàng của bạn. Chúng tôi sẽ\r\n"
				+ "                                                                            liên hệ lại ngay để xác nhận đơn hàng. <br>\r\n"
				+ "                                                                            <br>\r\n"
				+ "\r\n"
				+ "                                                                            Chúng tôi cam kết cung cấp dịch vụ tốt nhất\r\n"
				+ "                                                                            và sẽ liên tục cập nhật trạng thái của đơn\r\n"
				+ "                                                                            hàng cho bạn. Nếu bạn có bất kỳ câu hỏi nào,\r\n"
				+ "                                                                            vui lòng liên hệ với chúng tôi qua hệ thống\r\n"
				+ "                                                                            hỗ trợ hoặc số điện thoại hỗ trợ khách hàng.\r\n"
				+ "                                                                            <br> <br>\r\n"
				+ "\r\n"
				+ "                                                                            Một lần nữa, chúng tôi chân thành cảm ơn sự\r\n"
				+ "                                                                            ủng hộ của bạn và hy vọng bạn sẽ có trải\r\n"
				+ "                                                                            nghiệm mua sắm thú vị tại GamesVH! <br> <br>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "                                                                        </td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td style=\"text-align: right;\">Trân trọng,\r\n"
				+ "                                                                            Đội ngũ GamesVH</td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </center>\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "\r\n"
				+ "                                        </table>\r\n"
				+ "                                        <div style=\"margin-top: 60px; margin-bottom: 40px; border: 1px solid #e7e7e7;\">\r\n"
				+ "                                        </div>\r\n"
				+ "                                        <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\r\n"
				+ "                                            style=\"margin: 0 auto; margin-bottom: 40px;\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td style=\"text-align: left; padding-top: 15px; font-size: 1.5em;\">\r\n"
				+ "                                                        THÔNG TIN ĐƠN HÀNG</td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                        <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\r\n"
				+ "                                            style=\"margin: 0 auto; margin-bottom: 5px; margin-top: 20px;\">\r\n"
				+ "                                            <tbody style=\"text-align: center;\">\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <th>#</th>\r\n"
				+ "                                                    <th>SẢN PHẨM</th>\r\n"
				+ "                                                    <th>SỐ LƯỢNG</th>\r\n"
				+ "                                                    <th>ĐƠN GIÁ</th>\r\n"
				+ "                                                </tr>\r\n"
				+ 													orderDetail
				+ "                                                <tr>\r\n"
				+ "                                                    <td style=\"padding: 15px 0px;\"></td>\r\n"
				+ "                                                    <td style=\"padding: 15px 0px;\"></td>\r\n"
				+ "                                                    <td style=\"padding: 15px 0px;\">Vận chuyển</td>\r\n"
				+ "                                                    <td style=\"padding: 15px 0px;\">" + formatNumber(orderData.getShippingFee()) + " VND</td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td style=\"padding: 15px 0px; border-bottom: 1px solid #e7e7e7;\">\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                    <td style=\"padding: 15px 0px; border-bottom: 1px solid #e7e7e7;\">\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                    <td style=\"padding: 15px 0px; border-bottom: 1px solid #e7e7e7;\">\r\n"
				+ "                                                        Khuyến mãi</td>\r\n"
				+ "                                                    <td style=\"padding: 15px 0px; border-bottom: 1px solid #e7e7e7;\">\r\n"
				+ "                                                        "+ couponCode +"</td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                            <tfoot>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td style=\"padding-top: 20px;\">TỔNG TIỀN:</td>\r\n"
				+ "                                                    <td style=\"padding-top: 20px;\"></td>\r\n"
				+ "                                                    <td style=\"padding-top: 20px;\"></td>\r\n"
				+ "                                                    <td style=\"padding-top: 20px;\"><strong>" + formatNumber(orderData.getTotalPrice()) + " VND</strong></td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tfoot>\r\n"
				+ "                                        </table>\r\n"
				+ "                                        <div style=\"margin-top: 60px; margin-bottom: 40px; border: 1px solid #e7e7e7;\">\r\n"
				+ "                                        </div>\r\n"
				+ "                                        <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\r\n"
				+ "                                            style=\"margin: 0 auto; margin-bottom: 40px;\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td style=\"text-align: left; padding-top: 15px; font-size: 1.5em;\">\r\n"
				+ "                                                        THÔNG TIN KHÁCH HÀNG</td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                        <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\r\n"
				+ "                                            style=\"margin: 0 auto; margin-bottom: 5px; margin-top: 20px;\">\r\n"
				+ "                                            <tbody style=\"text-align: center;\">\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <th>ĐỊA CHỈ GIAO HÀNG</th>\r\n"
				+ "                                                    <th>ĐỊA CHỈ THANH TOÁN</th>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td>" + orderData.getFullname() + ", <br>\r\n"
				+ "                                                        " + orderData.getAddress() + "</td>\r\n"
				+ "                                                    <td>" + orderData.getFullname() + ", <br>\r\n"
				+ "                                                        " + orderData.getAddress() + "</td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                        <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\r\n"
				+ "                                            style=\"margin: 0 auto; margin-bottom: 40px; margin-top: 20px;\">\r\n"
				+ "                                            <tbody style=\"text-align: center;\">\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <th>PHƯƠNG THỨC VẬN CHUYỂN</th>\r\n"
				+ "                                                    <th>PHƯƠNG THỨC THANH TOÁN</th>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td>Giao hàng tận nơi</td>\r\n"
				+ "                                                    <td>" + orderData.getPaymentType() + "</td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                        <div style=\"margin-top: 20px; margin-bottom: 5px; border: 1px solid #e7e7e7;\">\r\n"
				+ "                                        </div>\r\n"
				+ "                                        <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\r\n"
				+ "                                            style=\"margin: 0 auto; margin-bottom: 5px;\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td style=\"text-align: justify; padding-top: 15px;\">\r\n"
				+ "                                                        <em> Nếu quý khách có bất cứ câu hỏi nào, đừng ngần ngại liên\r\n"
				+ "                                                            lạc với\r\n"
				+ "                                                            chúng tôi qua Tổng đài +0123 456 789. Đội ngũ GamesVH sẽ luôn sẵn\r\n"
				+ "                                                            sàng để hỗ trợ quý khách.</em>\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                            </tbody>\r\n"
				+ "                        </table>\r\n"
				+ "                    </center>\r\n"
				+ "                </td>\r\n"
				+ "            </tr>\r\n"
				+ "        </tbody>\r\n"
				+ "    </table>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
		return content;
	}
	
	 public static String formatNumber(Double number) {
	        DecimalFormat decimalFormat = new DecimalFormat("###,###");
	        return decimalFormat.format(number);
	 }
	 
	 public static String mail_TY(String fullname) {

			String welcome = "<!DOCTYPE html\r\n"
					+ "    PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
					+ "<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"
					+ "\r\n"
					+ "<head>\r\n"
					+ "    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\">\r\n"
					+ "    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
					+ "    <title>PropTech Kenya Welcome Email</title>\r\n"
					+ "    <!-- Designed by https://github.com/kaytcat --><!-- Robot header image designed by Freepik.com -->\r\n"
					+ "    <style type=\"text/css\">\r\n"
					+ "        @import url(https://fonts.googleapis.com/css?family=Nunito);\r\n"
					+ "\r\n"
					+ "        /* Take care of image borders and formatting */\r\n"
					+ "\r\n"
					+ "        img {\r\n"
					+ "            max-width: 600px;\r\n"
					+ "            outline: none;\r\n"
					+ "            text-decoration: none;\r\n"
					+ "            -ms-interpolation-mode: bicubic;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        html {\r\n"
					+ "            margin: 0;\r\n"
					+ "            padding: 0;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        a {\r\n"
					+ "            text-decoration: none;\r\n"
					+ "            border: 0;\r\n"
					+ "            outline: none;\r\n"
					+ "            color: #bbbbbb;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        a img {\r\n"
					+ "            border: none;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        /* General styling */\r\n"
					+ "\r\n"
					+ "        td,\r\n"
					+ "        h1,\r\n"
					+ "        h2,\r\n"
					+ "        h3 {\r\n"
					+ "            font-family: Helvetica, Arial, sans-serif;\r\n"
					+ "            font-weight: 400;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        td {\r\n"
					+ "            text-align: center;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        body {\r\n"
					+ "            -webkit-font-smoothing: antialiased;\r\n"
					+ "            -webkit-text-size-adjust: none;\r\n"
					+ "            width: 100%;\r\n"
					+ "            height: 100%;\r\n"
					+ "            color: #666;\r\n"
					+ "            background: #fff;\r\n"
					+ "            font-size: 16px;\r\n"
					+ "            height: 100vh;\r\n"
					+ "            width: 100%;\r\n"
					+ "            padding: 0px;\r\n"
					+ "            margin: 0px;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        table {\r\n"
					+ "            border-collapse: collapse !important;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        .headline {\r\n"
					+ "            color: #444;\r\n"
					+ "            font-size: 36px;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        .force-full-width {\r\n"
					+ "            width: 100% !important;\r\n"
					+ "        }\r\n"
					+ "    </style>\r\n"
					+ "    <style media=\"screen\" type=\"text/css\">\r\n"
					+ "        @media screen {\r\n"
					+ "\r\n"
					+ "            td,\r\n"
					+ "            h1,\r\n"
					+ "            h2,\r\n"
					+ "            h3 {\r\n"
					+ "                font-family: 'Nunito', 'Helvetica Neue', 'Arial', 'sans-serif' !important;\r\n"
					+ "            }\r\n"
					+ "        }\r\n"
					+ "    </style>\r\n"
					+ "    <style media=\"only screen and (max-width: 480px)\" type=\"text/css\">\r\n"
					+ "        /* Mobile styles */\r\n"
					+ "\r\n"
					+ "        @media only screen and (max-width: 480px) {\r\n"
					+ "\r\n"
					+ "            table[class=\"w320\"] {\r\n"
					+ "                width: 320px !important;\r\n"
					+ "            }\r\n"
					+ "        }\r\n"
					+ "    </style>\r\n"
					+ "\r\n"
					+ "</head>\r\n"
					+ "\r\n"
					+ "<body bgcolor=\"#fff\" class=\"body\"\r\n"
					+ "    style=\"padding:20px; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none\">\r\n"
					+ "    <table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\">\r\n"
					+ "        <tbody>\r\n"
					+ "            <tr>\r\n"
					+ "                <td align=\"center\" bgcolor=\"#fff\" class=\"\" valign=\"top\" width=\"100%\">\r\n"
					+ "                    <center class=\"\">\r\n"
					+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"w320\" style=\"margin: 0 auto;\" width=\"600\">\r\n"
					+ "                            <tbody>\r\n"
					+ "                                <tr>\r\n"
					+ "                                    <td align=\"center\" class=\"\" valign=\"top\">\r\n"
					+ "                                        <table cellpadding=\"0\" cellspacing=\"0\" style=\"margin: 0 auto;\" width=\"100%\">\r\n"
					+ "                                        </table>\r\n"
					+ "                                        <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"\"\r\n"
					+ "                                            style=\"margin: 0 auto; width: 100%; margin-top: 100px;\">\r\n"
					+ "                                            <tbody style=\"margin-top: 15px;\">\r\n"
					+ "                                                <tr class=\"\">\r\n"
					+ "                                                    <td class=\"\">\r\n"
					+ "                                                        <img alt=\"robot picture\" width=\"350\"\r\n"
					+ "                                                            src=\"https://lh3.googleusercontent.com/pw/AMWts8BE52AhhQd3jDG4W2RUxzaAq69PcixOhv_nV9VI2IxljwxzDHr6XShIYlSfq1io_5IdAJNePdcUHIDRzYcMJZFaYKf7N4e39CVIwWjUOcjVcW1ra2A4_oecW0PLytJyocXmFFNRAAtQQymNTGxxWD0=w960-h326\">\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                                <tr class=\"\">\r\n"
					+ "                                                    <td class=\"headline\" style=\"font-weight: 750;\">GAMESVH</td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td>\r\n"
					+ "                                                        <center class=\"\">\r\n"
					+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" class=\"\"\r\n"
					+ "                                                                style=\"margin: 0 auto; width: 75%;\">\r\n"
					+ "                                                                <tbody class=\"\">\r\n"
					+ "                                                                    <tr>\r\n"
					+ "                                                                        <td class=\"\"\r\n"
					+ "                                                                            style=\"color:#444; font-weight: 400; text-align: justify; padding-top: 15px;\">\r\n"
					+ "                                                                            <strong>Cám ơn bạn đã sử dụng website\r\n"
					+ "                                                                                GamesVH.</strong> <br> <br>\r\n"
					+ "\r\n"
					+ "                                                                            Xin chào "+fullname+", <br>\r\n"
					+ "                                                                            Chúng tôi xin gửi lời cảm ơn chân thành vì\r\n"
					+ "                                                                            sự đóng góp và góp ý quý báu mà bạn đã dành\r\n"
					+ "                                                                            thời gian để chia sẻ với chúng tôi. Đối với\r\n"
					+ "                                                                            chúng tôi, ý kiến và nhận xét của người dùng\r\n"
					+ "                                                                            là rất quan trọng và luôn đánh giá cao, bởi\r\n"
					+ "                                                                            nó giúp chúng tôi không ngừng cải thiện và\r\n"
					+ "                                                                            tối ưu hóa trải nghiệm của bạn trên website.\r\n"
					+ "                                                                            <br><br>\r\n"
					+ "\r\n"
					+ "                                                                            Nhờ những đóng góp của bạn, chúng tôi đã\r\n"
					+ "                                                                            nhận thấy những khía cạnh mà chúng tôi chưa\r\n"
					+ "                                                                            nhận ra trước đây và điều này giúp chúng tôi\r\n"
					+ "                                                                            xây dựng một trang web tốt hơn, đáp ứng tốt\r\n"
					+ "                                                                            hơn nhu cầu của người dùng và mang đến những\r\n"
					+ "                                                                            trải nghiệm tốt nhất cho mọi người.\r\n"
					+ "                                                                            <br><br>\r\n"
					+ "\r\n"
					+ "                                                                            Chúng tôi cam kết tiếp tục lắng nghe ý kiến\r\n"
					+ "                                                                            đóng góp của bạn và sẽ cùng nhau phát triển\r\n"
					+ "                                                                            website ngày càng hoàn thiện hơn. Nếu bạn có\r\n"
					+ "                                                                            bất kỳ góp ý hoặc câu hỏi nào khác, hãy đừng\r\n"
					+ "                                                                            ngần ngại liên hệ với chúng tôi. Chúng tôi\r\n"
					+ "                                                                            sẽ luôn sẵn lòng lắng nghe và giúp đỡ bạn.\r\n"
					+ "                                                                            <br><br>\r\n"
					+ "\r\n"
					+ "                                                                            Một lần nữa, cảm ơn bạn vì đã góp phần làm\r\n"
					+ "                                                                            cho website của chúng tôi trở nên tốt hơn và\r\n"
					+ "                                                                            hi vọng bạn sẽ tiếp tục ủng hộ và sử dụng\r\n"
					+ "                                                                            dịch vụ của chúng tôi.\r\n"
					+ "                                                                            <br><br>\r\n"
					+ "                                                                        </td>\r\n"
					+ "                                                                    </tr>\r\n"
					+ "                                                                    <tr>\r\n"
					+ "                                                                        <td style=\"text-align: right;\">Trân trọng,\r\n"
					+ "                                                                            Đội ngũ GamesVH</td>\r\n"
					+ "                                                                    </tr>\r\n"
					+ "                                                                </tbody>\r\n"
					+ "                                                            </table>\r\n"
					+ "                                                        </center>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "\r\n"
					+ "                                        </table>\r\n"
					+ "\r\n"
					+ "                                        <div style=\"margin-top: 20px; margin-bottom: 5px; border: 1px solid #e7e7e7;\">\r\n"
					+ "                                        </div>\r\n"
					+ "                                        <table bgcolor=\"#fff\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\r\n"
					+ "                                            style=\"margin: 0 auto; margin-bottom: 5px;\">\r\n"
					+ "                                            <tbody>\r\n"
					+ "                                                <tr>\r\n"
					+ "                                                    <td style=\"text-align: justify; padding-top: 15px;\">\r\n"
					+ "                                                        <em> Nếu quý khách có bất cứ câu hỏi nào, đừng ngần ngại liên\r\n"
					+ "                                                            lạc với\r\n"
					+ "                                                            chúng tôi qua Tổng đài +0123 456 789. Đội ngũ GamesVH sẽ\r\n"
					+ "                                                            luôn sẵn\r\n"
					+ "                                                            sàng để hỗ trợ quý khách.</em>\r\n"
					+ "                                                    </td>\r\n"
					+ "                                                </tr>\r\n"
					+ "                                            </tbody>\r\n"
					+ "                                        </table>\r\n"
					+ "                                    </td>\r\n"
					+ "                                </tr>\r\n"
					+ "                            </tbody>\r\n"
					+ "                        </table>\r\n"
					+ "                    </center>\r\n"
					+ "                </td>\r\n"
					+ "            </tr>\r\n"
					+ "        </tbody>\r\n"
					+ "    </table>\r\n"
					+ "</body>\r\n"
					+ "\r\n"
					+ "</html>";
			return welcome;
		}
}
